"""add status and payment_received to invoice

Revision ID: 26edb6ff3e01
Revises: 8df635896865
Create Date: 2026-03-08 23:15:06.044553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26edb6ff3e01'
down_revision = '8df635896865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_received', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('payment_received')

    # ### end Alembic commands ###
