"""add subcategory_name and category_name to invoice_item

Revision ID: 30bd36d33405
Revises: 795bdcf5f74c
Create Date: 2026-03-11 01:21:45.348983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bd36d33405'
down_revision = '795bdcf5f74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('category_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_column('category_name')
        batch_op.drop_column('subcategory_name')

    # ### end Alembic commands ###
