"""Add direct_price to InvoiceItem and profit helpers

Revision ID: 31b47d1de2df
Revises: d1b453427dcc
Create Date: 2026-01-13 22:54:51.157897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b47d1de2df'
down_revision = 'd1b453427dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direct_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_column('direct_price')

    # ### end Alembic commands ###
