"""add image_url, model_number, and serial_number to product

Revision ID: 795bdcf5f74c
Revises: 558615332fc0
Create Date: 2026-03-10 14:37:13.049870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795bdcf5f74c'
down_revision = '558615332fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('model_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('serial_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('serial_number')
        batch_op.drop_column('model_number')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
