"""add subcat and brand fields

Revision ID: 8deae92cb041
Revises: 31b47d1de2df
Create Date: 2026-03-08 19:38:10.827030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8deae92cb041'
down_revision = '31b47d1de2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('brand_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('brand_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('brand_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('brand_name')
        batch_op.drop_column('sub_category')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_column('brand_name')
        batch_op.drop_column('sub_category')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('brand_name')
        batch_op.drop_column('sub_category')

    # ### end Alembic commands ###
