"""restructure category hierarchy

Revision ID: 9104c5465419
Revises: 8deae92cb041
Create Date: 2026-03-08 20:26:16.779310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9104c5465419'
down_revision = '8deae92cb041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('sub_category')
        batch_op.drop_column('brand_name')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.String(length=36), nullable=True))
        batch_op.drop_column('sub_category')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.String(length=36), nullable=True))
        batch_op.drop_constraint(batch_op.f('products_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sub_categories', ['subcategory_id'], ['id'])
        batch_op.drop_column('sub_category')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('sub_category', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('products_ibfk_1'), 'categories', ['category_id'], ['id'])
        batch_op.drop_column('subcategory_id')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('sub_category', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('subcategory_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('sub_category', mysql.VARCHAR(length=100), nullable=True))

    op.drop_table('sub_categories')
    # ### end Alembic commands ###
