"""Update products and invoices with retail price and gst

Revision ID: d1b453427dcc
Revises: 8e8c3e94d979
Create Date: 2026-01-13 21:45:30.102023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1b453427dcc'
down_revision = '8e8c3e94d979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('gst_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.drop_column('unit_price')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('gst_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('gst_percentage')
        batch_op.drop_column('retail_price')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('gst_percentage')
        batch_op.drop_column('retail_price')

    # ### end Alembic commands ###
